---
id: 47094
name: Workspace 47094
description: An empty workspace.
revision: 44
lastModifiedDate: '2019-10-01T19:48:16Z'
lastModifiedUser: kunal.ganglani@aurea.com
lastModifiedAgent: structurizr-web/1624
model:
  people:
  - id: '7'
    tags: Element,Person
    name: Native Admin/ Portal Admin
    description: Manages Users, Groups, Logs, Database, Custom Fields, Metadata, Site
      Configuration
    relationships:
    - id: '115'
      tags: Relationship
      sourceId: '7'
      destinationId: '111'
      description: Customizes and configures
      interactionStyle: Synchronous
    - id: '12'
      tags: Relationship
      sourceId: '7'
      destinationId: '1'
      description: Manages User rights, Access, Groups, Store Rules, Metadata on
      technology: HTTP
      interactionStyle: Synchronous
    - id: '30'
      tags: Relationship
      sourceId: '7'
      destinationId: '18'
      description: Customizes and Configures
      interactionStyle: Synchronous
    location: Unspecified
  - id: '2'
    tags: Element,Person
    name: User
    relationships:
    - id: '29'
      tags: Relationship
      sourceId: '2'
      destinationId: '17'
      description: Manages Assets through
      technology: HTTP
      interactionStyle: Synchronous
    - id: '31'
      tags: Relationship
      sourceId: '2'
      destinationId: '19'
      description: Manages Assets through
      interactionStyle: Synchronous
    - id: '4'
      tags: Relationship
      sourceId: '2'
      destinationId: '1'
      description: Uploads/ Downloads/ Shares/ Converts/ Comments on Assets using
      technology: HTTP
      interactionStyle: Synchronous
    - id: '104'
      tags: Relationship
      sourceId: '2'
      destinationId: '102'
      description: Store and Retrieves Assets on Mounted Volumes via
      technology: SMB
      interactionStyle: Synchronous
    - id: '32'
      tags: Relationship
      sourceId: '2'
      destinationId: '20'
      description: Manages Assets through
      interactionStyle: Synchronous
    - id: '108'
      tags: Relationship
      sourceId: '2'
      destinationId: '100'
      description: Creates/ Edits Assets using
      interactionStyle: Synchronous
    location: Unspecified
  softwareSystems:
  - id: '8'
    tags: Element,Software System
    name: Adobe Create Cloud
    description: Adobe InDesign, Adobe Illustrator
    location: Unspecified
    containers:
    - id: '100'
      tags: Element,Container
      name: Adobe Creative Cloud
      technology: Adobe
      components:
      - id: '105'
        tags: Element,Component
        name: Adobe Illustrator
        size: 0
      - id: '106'
        tags: Element,Component
        name: Adobe In Design
        size: 0
  - id: '72'
    tags: Element,Software System
    name: Database
    location: Unspecified
    containers:
    - id: '101'
      tags: Element,Container
      name: Database
      technology: mySQL
  - id: '26'
    tags: Element,Software System
    name: File System
    description: Xinet File System storing the assets
    location: Unspecified
    containers:
    - id: '102'
      tags: Element,Container
      name: File System
      technology: SMB
  - id: '94'
    tags: Element,Software System
    name: Google Chrome Web Browser
    location: Unspecified
  - id: '15'
    tags: Element,Software System
    name: Mail Service
    description: Uses Postfix mail server to send XINET emails
    location: Unspecified
    containers:
    - id: '99'
      tags: Element,Container
      name: Mail Service
      technology: EMAIL
  - id: '1'
    tags: Element,Software System
    name: Northplains XINET Digital Asset Management System
    description: Digital Asset Management System that provides ability to store, manage,
      share and collaborate on Assets
    relationships:
    - id: '109'
      tags: Relationship
      sourceId: '1'
      destinationId: '8'
      description: allows asset edits on
      interactionStyle: Synchronous
    - id: '27'
      tags: Relationship
      sourceId: '1'
      destinationId: '26'
      description: Stores and Retrieves Assets from
      technology: HTTP
      interactionStyle: Synchronous
    - id: '16'
      tags: Relationship
      sourceId: '1'
      destinationId: '15'
      description: Sends Request to mail service to send emails to users
      technology: SMTP
      interactionStyle: Synchronous
    location: Unspecified
    containers:
    - id: '34'
      tags: Element,Container,ProjectID:XINET
      name: Xinet Client Apps
      description: Annotator ID, Metadata ID, Support ID, Picture Wrangler ID, Picture
        Wrangler AI, Contextual Menu Chrome, Contextual Menu Safari/ Finder
      relationships:
      - id: '107'
        tags: Relationship
        sourceId: '34'
        destinationId: '100'
        description: Provides Features to
        interactionStyle: Synchronous
      technology: JavaScript Browser Plugin
      components:
      - id: '80'
        tags: Element,Component,ProjectID:XINET
        name: Annotator ID
        size: 0
      - id: '85'
        tags: Element,Component,ProjectID:XINET
        name: Contextual Menu Chrome
        relationships:
        - id: '96'
          tags: Relationship
          sourceId: '85'
          destinationId: '94'
          description: Provides features to
          interactionStyle: Synchronous
        size: 0
      - id: '86'
        tags: Element,Component,ProjectID:XINET
        name: Contextual Menu Safari/ Finder
        relationships:
        - id: '97'
          tags: Relationship
          sourceId: '86'
          destinationId: '95'
          description: Provides features to
          interactionStyle: Synchronous
        size: 0
      - id: '81'
        tags: Element,Component,ProjectID:XINET
        name: Metadata ID
        size: 0
      - id: '84'
        tags: Element,Component,ProjectID:XINET
        name: Picture Wranger AI
        size: 0
      - id: '83'
        tags: Element,Component,ProjectID:XINET
        name: Picture Wrangler ID
        size: 0
      - id: '82'
        tags: Element,Component,ProjectID:XINET
        name: Support ID
        size: 0
    - id: '19'
      tags: Element,Container,ProjectID:XINET
      name: XINET Pilot MAC
      description: Desktop Front end for MAC that provides same Portal Functionalities
        including navtive OS features
      relationships:
      - id: '24'
        tags: Relationship
        sourceId: '19'
        destinationId: '17'
        description: Loads Pages (Pilot Theme) From
        technology: HTTP
        interactionStyle: Synchronous
      technology: C/C++
    - id: '20'
      tags: Element,Container,ProjectID:XINET
      name: XINET Pilot Windows
      description: Desktop Front end for Windows that provides same Portal Functionalities
        including navtive OS features
      relationships:
      - id: '23'
        tags: Relationship
        sourceId: '20'
        destinationId: '17'
        description: Loads Pages (Pilot Theme) From
        technology: HTTP
        interactionStyle: Synchronous
      technology: C/C++
    - id: '17'
      tags: Element,Container,ProjectID:XINET
      name: XINET Portal Web FrontEnd
      relationships:
      - id: '25'
        tags: Relationship
        sourceId: '17'
        destinationId: '18'
        description: Makes REST API Calls to
        technology: HTTP
        interactionStyle: Synchronous
      - id: '114'
        tags: Relationship
        sourceId: '17'
        destinationId: '111'
        description: Makes Rest API calls to
        technology: HTTP
        interactionStyle: Synchronous
      - id: '62'
        tags: Relationship
        sourceId: '17'
        destinationId: '46'
        description: uses
        interactionStyle: Synchronous
      technology: PHP
      components:
      - id: '42'
        tags: Element,Component,ProjectID:XINET
        name: Advanced Search
        description: Search with multiple options, powered by the native Fulltext
          search Engine (mySQL)
        technology: PHP
        size: 0
      - id: '49'
        tags: Element,Component,ProjectID:XINET
        name: Annotations
        description: Allows users to insert rectangles, flags and stamps on assets
        technology: PHP
        size: 0
      - id: '39'
        tags: Element,Component,ProjectID:XINET
        name: Collection
        description: Basket functionality where users can add multiple assets and
          apply operations on them in batch
        technology: PHP
        size: 0
      - id: '40'
        tags: Element,Component,ProjectID:XINET
        name: Collection Plugins
        description: Set of Plugins that provide the functionalities available in
          the Collection component
        technology: PHP
        size: 0
      - id: '46'
        tags: Element,Component,ProjectID:XINET
        name: Comments
        description: Provides comments on assets
        technology: PHP
        size: 0
      - id: '48'
        tags: Element,Component,ProjectID:XINET
        name: Filters (Path Search)
        description: Filter available for user based on Solr Facets (available when
          Solr is enabled)
        technology: PHP
        size: 0
      - id: '47'
        tags: Element,Component,ProjectID:XINET
        name: History
        description: Displays History info about the asset on XINET (user, access,
          operations performed etc)
        technology: PHP
        size: 0
      - id: '38'
        tags: Element,Component,ProjectID:XINET
        name: Login
        description: Provides Login, Remember Me, Forgot Password
        technology: PHP
        size: 0
      - id: '50'
        tags: Element,Component,ProjectID:XINET
        name: Metadata
        description: Displays metadata information and allows user to edit metadata
          of assets
        technology: PHP
        size: 0
      - id: '43'
        tags: Element,Component,ProjectID:XINET
        name: Navigator
        description: Navigator panel that displays the volumes and folders for quick
          navigation
        technology: PHP
        size: 0
      - id: '41'
        tags: Element,Component,ProjectID:XINET
        name: Quick Search
        description: Enhanced Search that can be powered by Solr (via XINET Server)
          if its enabled
        technology: PHP
        size: 0
      - id: '44'
        tags: Element,Component,ProjectID:XINET
        name: Upload Assets
        description: Provides upload functionalities for users
        technology: PHP
        size: 0
      - id: '45'
        tags: Element,Component,ProjectID:XINET
        name: Versions
        description: Allow users to manage different versions of the same asset
        technology: PHP
        size: 0
    - id: '18'
      tags: Element,Container,ProjectID:XIN
      name: XINET Server oold
      description: Ingests Assets, Generates Preview, Allow Transformations, Metadata
        Tagging, Manages Assets on File system (volumes)
      technology: C/C++
  - id: '95'
    tags: Element,Software System
    name: Safari Web Brower
    location: Unspecified
  - id: '74'
    tags: Element,Software System
    name: Solr
    description: Version 6.2.1
    location: Unspecified
  - id: '73'
    tags: Element,Software System
    name: webDBLog
    location: Unspecified
  - id: '110'
    tags: Element,Software System,ProjectID:XIN
    name: Xinet Server
    description: Ingests Assets, Generates Preview, Allow Transformations, Metadata
      Tagging, Manages Assets on File system (volumes)
    location: Unspecified
    containers:
    - id: '111'
      tags: Element,Container
      name: XINET Server
      description: Ingests Assets, Generates Preview, Allow Transformations, Metadata
        Tagging, Manages Assets on File system (volumes)
      relationships:
      - id: '113'
        tags: Relationship
        sourceId: '111'
        destinationId: '99'
        description: send email via
        technology: SMTP
        interactionStyle: Synchronous
      - id: '112'
        tags: Relationship
        sourceId: '111'
        destinationId: '102'
        description: Reads/ Writes Asset (Files) to
        interactionStyle: Synchronous
      technology: C/C++
  deploymentNodes: []
documentation:
  sections: []
  decisions: []
  images: []
views:
  systemContextViews:
  - softwareSystemId: '1'
    description: Xinet Portal System View
    key: XinetPortal
    paperSize: A5_Landscape
    animations:
    - order: 1
      elements:
      - '1'
      relationships: []
    - order: 2
      elements:
      - '2'
      - '7'
      - '8'
      relationships:
      - '11'
      - '12'
      - '4'
    - order: 3
      elements:
      - '15'
      relationships:
      - '16'
    - order: 4
      elements:
      - '26'
      relationships:
      - '27'
    enterpriseBoundaryVisible: true
    elements:
    - id: '1'
      x: 1065
      y: 715
    - id: '2'
      x: 685
      y: 20
    - id: '15'
      x: 1665
      y: 1255
    - id: '26'
      x: 530
      y: 1270
    - id: '7'
      x: 1535
      y: 25
    - id: '8'
      x: 145
      y: 720
    relationships:
    - id: '16'
    - id: '27'
    - id: '109'
    - id: '4'
    - id: '12'
  containerViews:
  - softwareSystemId: '1'
    key: XINETContainerView
    paperSize: A4_Landscape
    animations:
    - order: 1
      elements:
      - '2'
      - '17'
      - '7'
      - '19'
      - '20'
      relationships:
      - '23'
      - '24'
      - '29'
      - '31'
      - '32'
    - order: 2
      elements:
      - '34'
      relationships: []
    - order: 3
      elements:
      - '99'
      relationships: []
    - order: 4
      elements:
      - '102'
      relationships:
      - '104'
    - order: 5
      elements:
      - '100'
      relationships:
      - '107'
      - '108'
    - order: 6
      elements:
      - '111'
      relationships:
      - '112'
      - '113'
    elements:
    - id: '99'
      x: 2805
      y: 1780
    - id: '100'
      x: 140
      y: 85
    - id: '34'
      x: 155
      y: 980
    - id: '111'
      x: 1340
      y: 1800
    - id: '2'
      x: 1395
      y: 35
    - id: '102'
      x: 155
      y: 1840
    - id: '17'
      x: 1355
      y: 955
    - id: '7'
      x: 2605
      y: 30
    - id: '19'
      x: 2800
      y: 1245
    - id: '20'
      x: 2815
      y: 650
    relationships:
    - id: '32'
    - id: '31'
      vertices:
      - x: 2430
        y: 765
    - id: '29'
    - id: '108'
    - id: '107'
    - id: '24'
      vertices:
      - x: 2245
        y: 1410
    - id: '23'
    - id: '113'
    - id: '112'
    - id: '104'
    - id: '115'
      vertices:
      - x: 2560
        y: 1485
    - id: '114'
  componentViews:
  - softwareSystemId: '1'
    key: XinetPortalComponentView
    paperSize: A4_Landscape
    animations:
    - order: 1
      elements:
      - '46'
      relationships: []
    - order: 2
      elements:
      - '44'
      - '45'
      - '47'
      - '48'
      - '38'
      - '49'
      - '39'
      - '50'
      - '40'
      - '41'
      - '42'
      - '43'
      relationships: []
    containerId: '17'
    elements:
    - id: '44'
      x: 1720
      y: 60
    - id: '45'
      x: 295
      y: 475
    - id: '46'
      x: 1720
      y: 970
    - id: '47'
      x: 1015
      y: 520
    - id: '48'
      x: 290
      y: 935
    - id: '38'
      x: 285
      y: 60
    - id: '49'
      x: 1005
      y: 950
    - id: '39'
      x: 1000
      y: 1925
    - id: '50'
      x: 1725
      y: 510
    - id: '40'
      x: 300
      y: 1425
    - id: '41'
      x: 980
      y: 1425
    - id: '42'
      x: 1700
      y: 1440
    - id: '43'
      x: 1000
      y: 50
    relationships: []
  - softwareSystemId: '1'
    description: Xinet Client Apps Component View
    key: XinetClientAppsComponentView
    paperSize: A3_Landscape
    animations:
    - order: 1
      elements:
      - '80'
      - '81'
      - '82'
      - '83'
      - '84'
      - '85'
      - '86'
      relationships: []
    - order: 2
      elements:
      - '88'
      - '87'
      relationships:
      - '89'
      - '90'
      - '91'
      - '92'
      - '93'
    - order: 3
      elements:
      - '94'
      - '95'
      relationships: []
    containerId: '34'
    elements:
    - id: '80'
      x: 1605
      y: 935
    - id: '81'
      x: 2285
      y: 950
    - id: '82'
      x: 990
      y: 930
    - id: '83'
      x: 390
      y: 925
    - id: '94'
      x: 2970
      y: 1595
    - id: '84'
      x: 4150
      y: 945
    - id: '95'
      x: 3605
      y: 1590
    - id: '85'
      x: 2980
      y: 950
    - id: '86'
      x: 3565
      y: 950
    relationships:
    - id: '97'
    - id: '96'
  configuration:
    branding: {}
    styles:
      elements:
      - tag: Person
        background: "#8080ff"
        color: "#ffffff"
        shape: Person
      - tag: Software System
        background: "#0000a0"
        color: "#ffffff"
        shape: RoundedBox
      - tag: Component
        background: "#008040"
        color: "#ffffff"
        shape: Box
      relationships: []
    terminology: {}
    lastSavedView: XINETContainerView
  systemLandscapeViews: []
  dynamicViews: []
  deploymentViews: []
  filteredViews: []
