manager: Alexey Syrtsev
teamroom: Eng.ProductCA
units:
    - unit: https://jira.devfactory.com/issues/?jql=type%20%3D%20%22Eng%20Problem%22%20and%20%22Eng.Problem%20Category%22%20%3D%20%22Architecture%20doc%22%20
automation:
    product agnostic: true
    product specific:
        ##- product name: !!str #product names
    description: Arch docs should be linked to the product structure. So, Arch Docs generation shouldn't go in 'Deliver anything 5 times' direction. PCA should define a product structure yaml file. Then, each arch doc should be generated to cover an aspect of an item in that file. Once coverage is done, product is considered as documented. Once PCA changes yaml file (because of new feature or discovered gap) - a new bunch of Arch Doc tasks can be generated
    effort: 5 #days
    impact: 15 #or more - depending on product structure definition
