manager: Alexey Syrtsev
teamroom: Eng.Product,Eng.Feature,Eng.Maintenance,Eng.Faster
units: 
    - unit: https://jira.devfactory.com/issues/?jql=type%20in%20(%22Feature%20Story%22%2C%22Faster%20Story%22%2C%22Customer%20Defect%22%2CDefect)
automation:
    product agnostic: true
    product specific: 
        ##- product name: !!str #product names
    description: We should change our delivery approach from 'Release what is delivered' to 'Deliver what is planned to be released'. Hence, work queues for Feature, Maintenance and Faster should be introduced and prioritized (with Due Dates) according to fixVersions. FixVersions can be defined by PSEMs/PCAs only. It should help Product temas to keep core teams focused on planned deliverables rather than on Core SEMs personal preferences
    effort: 10 #days
    impact: 10 #or more - depending on product structure definition
