manager: Bugra Kara
teamroom: Eng.QAManualTesting
units:
    - unit: https://jira.devfactory.com/browse/AUTO-1971
automation:
    product agnostic: true
    product specific:
        - product name: N/A
    description: Delink Invalid Test Cases
    effort: 3
    impact: 10
