manager: Carlos Witte
teamroom: Eng.DevSpacesImport
units: 
    - unit: https://jira.devfactory.com/issues/?filter=94041
automation: 
    product agnostic: true
    product specific: 
        - product name: null
    description: VSCode plugin to hide DevSpaces overhead and improve the developers experience.
    effort: 61
    impact: 0.10
