manager: Dmitry Frolov
teamroom: Eng.Manager
units: 
    - unit: jira ticket is not created yet for this
automation: simplify PSEM yaml creation
    product agnostic: false
    product specific: 
        - product name: all
    description: develop a simple front end to create yaml files for managers
      this should save 30s-1minute from each yaml, which is about 5k$ savings
      on a year for 36 people and 30s saving - 2 weeks of 1 SEM 
    effort: 1
    impact: 0.11
