manager: Dmytro Malenko
teamroom: Eng.Feature
units: 
    - unit: https://jira.devfactory.com/browse/JCLDALL-17495
automation: 
    product agnostic: false
    product specific:
        - product name: Jive Cloud
    description: Automate provisioning and deletion of DNS domains used to simulate customers' custom domains for development and testing purposes. 
    effort: 2
    impact: 5
