manager: Egor Blinov
teamroom: Optiva.Eng.Feature
units:
    - unit: https://jira.optiva.com/jira/browse/OMNT-2888
automation:
    product agnostic: true
    product specific:
        - product name: Unified
    description: Send ticket back to development automatically once regression completes related TC's and coverage is failing
    effort: 4
    impact: 2

