manager: Ines Guisado
teamroom: Eng.QAIntegrationTesting
units:
    - unit: https://jira.devfactory.com/browse/QAP-8619
automation:
    product agnostic: true
    product specific:
        - product name: null
    description: Git hooks to automate the creation of PRs. In implementation.
    effort: 4
    impact: 15.0