manager: Ivan Golovanov
teamroom: Eng.QAIntegrationTesting
units:
    - unit: https://jira.devfactory.com/browse/AESCIS-40865
automation:
    product agnostic: true
    product specific:
        - product name: AES CIS
    description: Create testing tickets automaticly for every TC
    effort: 3
    impact: 1
