manager: John Isaac
teamroom: Eng.CodeReview.QC
units: 
    - unit: All
automation:
    product agnostic: true
    description: Decouple CodeReview tools from JIRA
    effort: 30
    impact: 18.75 to 25 # around 2-3 min. per unit