manager: Konstantin Korotaev
teamroom: Eng.ProductCA
units: 
    - unit: https://jira.devfactory.com/browse/NORTHP-20136
    - unit: https://jira.devfactory.com/browse/NORTHP-16527
    - unit: https://jira.devfactory.com/browse/NORTHP-16289
automation: 
    product agnostic: true
    product specific: 
        - product name: Northplains Telescope
    description: Add environment details (link\IP, credentials) to end to end tests from Jenkins\YAML 
    effort: 1
    impact: 2