manager: Mitesh Kamdar
teamroom: Eng.Feature
units:
    - unit: https://jira.devfactory.com/browse/MFR-2277
automation:
    product agnostic: true
    product specific:
        - product name: FogBugz 5K Rewrite
    description: Working with PCA to configure auto notifications on build failure so that ICs can pro-actively fix the issues, rather than getting feedback from QE or PCA and then fix it
    effort: 1
    impact: 5


