manager: Todd Benson
teamroom: Eng.ProductCA
units: 3
    - https://jira.devfactory.com/browse/STRONGTEST-48
    - https://jira.devfactory.com/browse/STRONGTEST-49
    - https://jira.devfactory.com/browse/STRONGTEST-50
automation: 
    product agnostic: true
    product specific: 
        - product name: StrongTest
    description: To create documentation and get credit for, ICs currently manually update the documentation, then they create a Eng.Problem ticket and update it with information that was updated in the ticket.  We should create an automation so that user manually updates the documentation first, then they highlight what they have updated in doc, right click, see a menu that says something like "Create an Eng.Problem ticket of Arch doc type" and select this option.  This will create the Eng.Problem ticket, fill out all details and submit it for QE review.  This will save 5 minutes a ticket or 15 minutes a day and will help all PCAs save this time.
    effort: 3 days
    impact: 100% of PCAs can affected positively, saving 15 minutes a day.